//go:build ignore

package winhello

/*
//#cgo CFLAGS: -I${SRCDIR}

#include <windows.h>
#include <webauthn.h>
*/
import "C"

type (
	_GUID                                           C.GUID
	_WEBAUTHN_ASSERTION                             C.WEBAUTHN_ASSERTION
	_WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS   C.WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS
	_WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS C.WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS
	_WEBAUTHN_CLIENT_DATA                           C.WEBAUTHN_CLIENT_DATA
	_WEBAUTHN_COMMON_ATTESTATION                    C.WEBAUTHN_COMMON_ATTESTATION
	_WEBAUTHN_COSE_CREDENTIAL_PARAMETER             C.WEBAUTHN_COSE_CREDENTIAL_PARAMETER
	_WEBAUTHN_COSE_CREDENTIAL_PARAMETERS            C.WEBAUTHN_COSE_CREDENTIAL_PARAMETERS
	_WEBAUTHN_CRED_BLOB_EXTENSION                   C.WEBAUTHN_CRED_BLOB_EXTENSION
	_WEBAUTHN_CRED_PROTECT_EXTENSION_IN             C.WEBAUTHN_CRED_PROTECT_EXTENSION_IN
	_WEBAUTHN_CRED_WITH_HMAC_SECRET_SALT            C.WEBAUTHN_CRED_WITH_HMAC_SECRET_SALT
	_WEBAUTHN_CREDENTIAL                            C.WEBAUTHN_CREDENTIAL
	_WEBAUTHN_CREDENTIAL_ATTESTATION                C.WEBAUTHN_CREDENTIAL_ATTESTATION
	_WEBAUTHN_CREDENTIAL_DETAILS                    C.WEBAUTHN_CREDENTIAL_DETAILS
	_WEBAUTHN_CREDENTIAL_DETAILS_LIST               C.WEBAUTHN_CREDENTIAL_DETAILS_LIST
	_WEBAUTHN_CREDENTIAL_EX                         C.WEBAUTHN_CREDENTIAL_EX
	_WEBAUTHN_CREDENTIAL_LIST                       C.WEBAUTHN_CREDENTIAL_LIST
	_WEBAUTHN_CREDENTIALS                           C.WEBAUTHN_CREDENTIALS
	_WEBAUTHN_EXTENSION                             C.WEBAUTHN_EXTENSION
	_WEBAUTHN_EXTENSIONS                            C.WEBAUTHN_EXTENSIONS
	_WEBAUTHN_GET_CREDENTIALS_OPTIONS               C.WEBAUTHN_GET_CREDENTIALS_OPTIONS
	_WEBAUTHN_HMAC_SECRET_SALT                      C.WEBAUTHN_HMAC_SECRET_SALT
	_WEBAUTHN_HMAC_SECRET_SALT_VALUES               C.WEBAUTHN_HMAC_SECRET_SALT_VALUES
	_WEBAUTHN_RP_ENTITY_INFORMATION                 C.WEBAUTHN_RP_ENTITY_INFORMATION
	_WEBAUTHN_USER_ENTITY_INFORMATION               C.WEBAUTHN_USER_ENTITY_INFORMATION
	_WEBAUTHN_X5C                                   C.WEBAUTHN_X5C
	_CTAPCBOR_HYBRID_STORAGE_LINKED_DATA            C.CTAPCBOR_HYBRID_STORAGE_LINKED_DATA
	_WEBAUTHN_AUTHENTICATOR_DETAILS_OPTIONS         C.WEBAUTHN_AUTHENTICATOR_DETAILS_OPTIONS
	_WEBAUTHN_AUTHENTICATOR_DETAILS                 C.WEBAUTHN_AUTHENTICATOR_DETAILS
	_WEBAUTHN_AUTHENTICATOR_DETAILS_LIST            C.WEBAUTHN_AUTHENTICATOR_DETAILS_LIST
)

func int32ToBool(i int32) bool {
	return i != 0
}

func boolToInt32(b bool) int32 {
	if b {
		return 1
	}
	return 0
}
