// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo.exe -godefs types_webauthn.go

package winhello

import "golang.org/x/sys/windows"

type (
	_WEBAUTHN_ASSERTION struct {
		DwVersion                    uint32
		CbAuthenticatorData          uint32
		PbAuthenticatorData          *uint8
		CbSignature                  uint32
		PbSignature                  *uint8
		Credential                   _WEBAUTHN_CREDENTIAL
		CbUserId                     uint32
		PbUserId                     *uint8
		Extensions                   _WEBAUTHN_EXTENSIONS
		CbCredLargeBlob              uint32
		PbCredLargeBlob              *uint8
		DwCredLargeBlobStatus        uint32
		PHmacSecret                  *_WEBAUTHN_HMAC_SECRET_SALT
		DwUsedTransport              uint32
		CbUnsignedExtensionOutputs   uint32
		PbUnsignedExtensionOutputs   *uint8
		CbClientDataJSON             uint32
		PbClientDataJSON             *uint8
		CbAuthenticationResponseJSON uint32
		PbAuthenticationResponseJSON *uint8
	}
	_WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS struct {
		DwVersion                               uint32
		DwTimeoutMilliseconds                   uint32
		CredentialList                          _WEBAUTHN_CREDENTIALS
		Extensions                              _WEBAUTHN_EXTENSIONS
		DwAuthenticatorAttachment               uint32
		DwUserVerificationRequirement           uint32
		DwFlags                                 uint32
		PwszU2fAppId                            *uint16
		PbU2fAppId                              *int32
		PCancellationId                         *windows.GUID
		PAllowCredentialList                    *_WEBAUTHN_CREDENTIAL_LIST
		DwCredLargeBlobOperation                uint32
		CbCredLargeBlob                         uint32
		PbCredLargeBlob                         *uint8
		PHmacSecretSaltValues                   *_WEBAUTHN_HMAC_SECRET_SALT_VALUES
		BBrowserInPrivateMode                   int32
		PLinkedDevice                           *_CTAPCBOR_HYBRID_STORAGE_LINKED_DATA
		BAutoFill                               int32
		CbJsonExt                               uint32
		PbJsonExt                               *uint8
		CCredentialHints                        uint32
		PpwszCredentialHints                    **uint16
		PwszRemoteWebOrigin                     *uint16
		CbPublicKeyCredentialRequestOptionsJSON uint32
		PbPublicKeyCredentialRequestOptionsJSON *uint8
		CbAuthenticatorId                       uint32
		PbAuthenticatorId                       *uint8
	}
	_WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS struct {
		DwVersion                                uint32
		DwTimeoutMilliseconds                    uint32
		CredentialList                           _WEBAUTHN_CREDENTIALS
		Extensions                               _WEBAUTHN_EXTENSIONS
		DwAuthenticatorAttachment                uint32
		BRequireResidentKey                      int32
		DwUserVerificationRequirement            uint32
		DwAttestationConveyancePreference        uint32
		DwFlags                                  uint32
		PCancellationId                          *windows.GUID
		PExcludeCredentialList                   *_WEBAUTHN_CREDENTIAL_LIST
		DwEnterpriseAttestation                  uint32
		DwLargeBlobSupport                       uint32
		BPreferResidentKey                       int32
		BBrowserInPrivateMode                    int32
		BEnablePrf                               int32
		PLinkedDevice                            *_CTAPCBOR_HYBRID_STORAGE_LINKED_DATA
		CbJsonExt                                uint32
		PbJsonExt                                *uint8
		PPRFGlobalEval                           *_WEBAUTHN_HMAC_SECRET_SALT
		CCredentialHints                         uint32
		PpwszCredentialHints                     **uint16
		BThirdPartyPayment                       int32
		PwszRemoteWebOrigin                      *uint16
		CbPublicKeyCredentialCreationOptionsJSON uint32
		PbPublicKeyCredentialCreationOptionsJSON *uint8
		CbAuthenticatorId                        uint32
		PbAuthenticatorId                        *uint8
	}
	_WEBAUTHN_CLIENT_DATA struct {
		DwVersion        uint32
		CbClientDataJSON uint32
		PbClientDataJSON *uint8
		PwszHashAlgId    *uint16
	}
	_WEBAUTHN_COMMON_ATTESTATION struct {
		DwVersion   uint32
		PwszAlg     *uint16
		LAlg        int32
		CbSignature uint32
		PbSignature *uint8
		CX5c        uint32
		PX5c        *_WEBAUTHN_X5C
		PwszVer     *uint16
		CbCertInfo  uint32
		PbCertInfo  *uint8
		CbPubArea   uint32
		PbPubArea   *uint8
	}
	_WEBAUTHN_COSE_CREDENTIAL_PARAMETER struct {
		DwVersion          uint32
		PwszCredentialType *uint16
		LAlg               int32
		Pad_cgo_0          [4]byte
	}
	_WEBAUTHN_COSE_CREDENTIAL_PARAMETERS struct {
		CCredentialParameters uint32
		PCredentialParameters *_WEBAUTHN_COSE_CREDENTIAL_PARAMETER
	}
	_WEBAUTHN_CRED_BLOB_EXTENSION struct {
		CbCredBlob uint32
		PbCredBlob *uint8
	}
	_WEBAUTHN_CRED_PROTECT_EXTENSION_IN struct {
		DwCredProtect       uint32
		BRequireCredProtect int32
	}
	_WEBAUTHN_CRED_WITH_HMAC_SECRET_SALT struct {
		CbCredID        uint32
		PbCredID        *uint8
		PHmacSecretSalt *_WEBAUTHN_HMAC_SECRET_SALT
	}
	_WEBAUTHN_CREDENTIAL struct {
		DwVersion          uint32
		CbId               uint32
		PbId               *uint8
		PwszCredentialType *uint16
	}
	_WEBAUTHN_CREDENTIAL_ATTESTATION struct {
		DwVersion                  uint32
		PwszFormatType             *uint16
		CbAuthenticatorData        uint32
		PbAuthenticatorData        *uint8
		CbAttestation              uint32
		PbAttestation              *uint8
		DwAttestationDecodeType    uint32
		PvAttestationDecode        *byte
		CbAttestationObject        uint32
		PbAttestationObject        *uint8
		CbCredentialId             uint32
		PbCredentialId             *uint8
		Extensions                 _WEBAUTHN_EXTENSIONS
		DwUsedTransport            uint32
		BEpAtt                     int32
		BLargeBlobSupported        int32
		BResidentKey               int32
		BPrfEnabled                int32
		CbUnsignedExtensionOutputs uint32
		PbUnsignedExtensionOutputs *uint8
		PHmacSecret                *_WEBAUTHN_HMAC_SECRET_SALT
		BThirdPartyPayment         int32
		DwTransports               uint32
		CbClientDataJSON           uint32
		PbClientDataJSON           *uint8
		CbRegistrationResponseJSON uint32
		PbRegistrationResponseJSON *uint8
	}
	_WEBAUTHN_CREDENTIAL_DETAILS struct {
		DwVersion             uint32
		CbCredentialID        uint32
		PbCredentialID        *uint8
		PRpInformation        *_WEBAUTHN_RP_ENTITY_INFORMATION
		PUserInformation      *_WEBAUTHN_USER_ENTITY_INFORMATION
		BRemovable            int32
		BBackedUp             int32
		PwszAuthenticatorName *uint16
		CbAuthenticatorLogo   uint32
		PbAuthenticatorLogo   *uint8
		BThirdPartyPayment    int32
		DwTransports          uint32
	}
	_WEBAUTHN_CREDENTIAL_DETAILS_LIST struct {
		CCredentialDetails  uint32
		PpCredentialDetails **_WEBAUTHN_CREDENTIAL_DETAILS
	}
	_WEBAUTHN_CREDENTIAL_EX struct {
		DwVersion          uint32
		CbId               uint32
		PbId               *uint8
		PwszCredentialType *uint16
		DwTransports       uint32
		Pad_cgo_0          [4]byte
	}
	_WEBAUTHN_CREDENTIAL_LIST struct {
		CCredentials  uint32
		PpCredentials **_WEBAUTHN_CREDENTIAL_EX
	}
	_WEBAUTHN_CREDENTIALS struct {
		CCredentials uint32
		PCredentials *_WEBAUTHN_CREDENTIAL
	}
	_WEBAUTHN_EXTENSION struct {
		PwszExtensionIdentifier *uint16
		CbExtension             uint32
		PvExtension             *byte
	}
	_WEBAUTHN_EXTENSIONS struct {
		CExtensions uint32
		PExtensions *_WEBAUTHN_EXTENSION
	}
	_WEBAUTHN_GET_CREDENTIALS_OPTIONS struct {
		DwVersion             uint32
		PwszRpId              *uint16
		BBrowserInPrivateMode int32
		Pad_cgo_0             [4]byte
	}
	_WEBAUTHN_HMAC_SECRET_SALT struct {
		CbFirst  uint32
		PbFirst  *uint8
		CbSecond uint32
		PbSecond *uint8
	}
	_WEBAUTHN_HMAC_SECRET_SALT_VALUES struct {
		PGlobalHmacSalt             *_WEBAUTHN_HMAC_SECRET_SALT
		CCredWithHmacSecretSaltList uint32
		PCredWithHmacSecretSaltList *_WEBAUTHN_CRED_WITH_HMAC_SECRET_SALT
	}
	_WEBAUTHN_RP_ENTITY_INFORMATION struct {
		DwVersion uint32
		PwszId    *uint16
		PwszName  *uint16
		PwszIcon  *uint16
	}
	_WEBAUTHN_USER_ENTITY_INFORMATION struct {
		DwVersion       uint32
		CbId            uint32
		PbId            *uint8
		PwszName        *uint16
		PwszIcon        *uint16
		PwszDisplayName *uint16
	}
	_WEBAUTHN_X5C struct {
		CbData uint32
		PbData *uint8
	}
	_CTAPCBOR_HYBRID_STORAGE_LINKED_DATA struct {
		DwVersion                  uint32
		CbContactId                uint32
		PbContactId                *uint8
		CbLinkId                   uint32
		PbLinkId                   *uint8
		CbLinkSecret               uint32
		PbLinkSecret               *uint8
		CbPublicKey                uint32
		PbPublicKey                *uint8
		PwszAuthenticatorName      *uint16
		WEncodedTunnelServerDomain uint16
		Pad_cgo_0                  [6]byte
	}
	_WEBAUTHN_AUTHENTICATOR_DETAILS_OPTIONS struct {
		DwVersion uint32
	}
	_WEBAUTHN_AUTHENTICATOR_DETAILS struct {
		DwVersion             uint32
		CbAuthenticatorId     uint32
		PbAuthenticatorId     *uint8
		PwszAuthenticatorName *uint16
		CbAuthenticatorLogo   uint32
		PbAuthenticatorLogo   *uint8
		BLocked               int32
		Pad_cgo_0             [4]byte
	}
	_WEBAUTHN_AUTHENTICATOR_DETAILS_LIST struct {
		CAuthenticatorDetails  uint32
		PpAuthenticatorDetails **_WEBAUTHN_AUTHENTICATOR_DETAILS
	}

	_WEBAUTHN_PLUGIN_ADD_AUTHENTICATOR_OPTIONS struct {
		PwszAuthenticatorName *uint16
		Rclsid                *windows.GUID
		PwszPluginRpId        *uint16
		PwszLightThemeLogoSvg *uint16
		PwszDarkThemeLogoSvg  *uint16
		CbAuthenticatorInfo   uint32
		PbAuthenticatorInfo   *uint8
		CSupportedRpIds       uint32
		PpwszSupportedRpIds   **uint16
	}
	_WEBAUTHN_PLUGIN_ADD_AUTHENTICATOR_RESPONSE struct {
		CbOpSignPubKey uint32
		PbOpSignPubKey *uint8
	}
	_WEBAUTHN_PLUGIN_UPDATE_AUTHENTICATOR_DETAILS struct {
		PwszAuthenticatorName *uint16
		Rclsid                *windows.GUID
		RclsidNew             *windows.GUID
		PwszLightThemeLogoSvg *uint16
		PwszDarkThemeLogoSvg  *uint16
		CbAuthenticatorInfo   uint32
		PbAuthenticatorInfo   *uint8
		CSupportedRpIds       uint32
		PpwszSupportedRpIds   **uint16
	}
	_WEBAUTHN_PLUGIN_CREDENTIAL_DETAILS struct {
		CbCredentialId      uint32
		PbCredentialId      *uint8
		PwszRpId            *uint16
		PwszRpName          *uint16
		CbUserId            uint32
		PbUserId            *uint8
		PwszUserName        *uint16
		PwszUserDisplayName *uint16
	}
	_WEBAUTHN_PLUGIN_USER_VERIFICATION_REQUEST struct {
		Hwnd               windows.HWND
		RguidTransactionId *windows.GUID
		PwszUsername       *uint16
		PwszDisplayHint    *uint16
	}
	_WEBAUTHN_CTAPCBOR_AUTHENTICATOR_OPTIONS struct {
		DwVersion           uint32
		LUp                 int32
		LUv                 int32
		LRequireResidentKey int32
	}
	_WEBAUTHN_CTAPCBOR_ECC_PUBLIC_KEY struct {
		DwVersion uint32
		LKty      int32
		LAlg      int32
		LCrv      int32
		CbX       uint32
		PbX       *uint8
		CbY       uint32
		PbY       *uint8
	}
	_WEBAUTHN_CTAPCBOR_HMAC_SALT_EXTENSION struct {
		DwVersion       uint32
		PKeyAgreement   *_WEBAUTHN_CTAPCBOR_ECC_PUBLIC_KEY
		CbEncryptedSalt uint32
		PbEncryptedSalt *uint8
		CbSaltAuth      uint32
		PbSaltAuth      *uint8
	}
	_WEBAUTHN_CTAPCBOR_MAKE_CREDENTIAL_REQUEST struct {
		DwVersion                    uint32
		CbRpId                       uint32
		PbRpId                       *uint8
		CbClientDataHash             uint32
		PbClientDataHash             *uint8
		PRpInformation               *_WEBAUTHN_RP_ENTITY_INFORMATION
		PUserInformation             *_WEBAUTHN_USER_ENTITY_INFORMATION
		WebAuthNCredentialParameters _WEBAUTHN_COSE_CREDENTIAL_PARAMETERS
		CredentialList               _WEBAUTHN_CREDENTIAL_LIST
		CbCborExtensionsMap          uint32
		PbCborExtensionsMap          *uint8
		PAuthenticatorOptions        *_WEBAUTHN_CTAPCBOR_AUTHENTICATOR_OPTIONS
		FEmptyPinAuth                int32
		CbPinAuth                    uint32
		PbPinAuth                    *uint8
		LHmacSecretExt               int32
		PHmacSecretMcExtension       *_WEBAUTHN_CTAPCBOR_HMAC_SALT_EXTENSION
		LPrfExt                      int32
		CbHmacSecretSaltValues       uint32
		PbHmacSecretSaltValues       *uint8
		DwCredProtect                uint32
		DwPinProtocol                uint32
		DwEnterpriseAttestation      uint32
		CbCredBlobExt                uint32
		PbCredBlobExt                *uint8
		LLargeBlobKeyExt             int32
		DwLargeBlobSupport           uint32
		LMinPinLengthExt             int32
		CbJsonExt                    uint32
		PbJsonExt                    *uint8
	}
	_WEBAUTHN_CTAPCBOR_GET_ASSERTION_REQUEST struct {
		DwVersion                   uint32
		PwszRpId                    *uint16
		CbRpId                      uint32
		PbRpId                      *uint8
		CbClientDataHash            uint32
		PbClientDataHash            *uint8
		CredentialList              _WEBAUTHN_CREDENTIAL_LIST
		CbCborExtensionsMap         uint32
		PbCborExtensionsMap         *uint8
		PAuthenticatorOptions       *_WEBAUTHN_CTAPCBOR_AUTHENTICATOR_OPTIONS
		FEmptyPinAuth               int32
		CbPinAuth                   uint32
		PbPinAuth                   *uint8
		PHmacSaltExtension          *_WEBAUTHN_CTAPCBOR_HMAC_SALT_EXTENSION
		CbHmacSecretSaltValues      uint32
		PbHmacSecretSaltValues      *uint8
		DwPinProtocol               uint32
		LCredBlobExt                int32
		LLargeBlobKeyExt            int32
		DwCredLargeBlobOperation    uint32
		CbCredLargeBlobCompressed   uint32
		PbCredLargeBlobCompressed   *uint8
		DwCredLargeBlobOriginalSize uint32
		CbJsonExt                   uint32
		PbJsonExt                   *uint8
	}
	_WEBAUTHN_CTAPCBOR_GET_ASSERTION_RESPONSE struct {
		WebAuthNAssertion          _WEBAUTHN_ASSERTION
		PUserInformation           *_WEBAUTHN_USER_ENTITY_INFORMATION
		DwNumberOfCredentials      uint32
		LUserSelected              int32
		CbLargeBlobKey             uint32
		PbLargeBlobKey             *uint8
		CbUnsignedExtensionOutputs uint32
		PbUnsignedExtensionOutputs *uint8
	}
)

func int32ToBool(i int32) bool {
	return i != 0
}

func boolToInt32(b bool) int32 {
	if b {
		return 1
	}
	return 0
}
