// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo.exe -godefs types_pluginauthenticator.go

package main

import "golang.org/x/sys/windows"

type (
	_WEBAUTHN_PLUGIN_OPERATION_REQUEST struct {
		HWnd               windows.HWND
		TransactionId      windows.GUID
		CbRequestSignature uint32
		PbRequestSignature *uint8
		RequestType        uint32
		CbEncodedRequest   uint32
		PbEncodedRequest   *uint8
	}
	_WEBAUTHN_PLUGIN_OPERATION_RESPONSE struct {
		CbEncodedResponse uint32
		PbEncodedResponse *uint8
	}
	_WEBAUTHN_PLUGIN_CANCEL_OPERATION_REQUEST struct {
		TransactionId      windows.GUID
		CbRequestSignature uint32
		PbRequestSignature *uint8
	}
)

func int32ToBool(i int32) bool {
	return i != 0
}

func boolToInt32(b bool) int32 {
	if b {
		return 1
	}
	return 0
}
